name: csv-update

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          setup-python: 3.7
      - name: Install dependencies
        run: pip install requests
      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.email "GitHub Action"
      - name: Synchronize the csv file with an up-to-date one
        run: |
          cd make-json
          python download.py
      - name: git commit
        run: |
          git add .
          git commit -m "update csv"
      - name: git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}