name: csv-update

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        run: ls -a